function [fitresult, gof] = createFit(feedBackVoltage, inputAngle)
%CREATEFIT(FEEDBACKVOLTAGE,INPUTANGLE)
%  Create a fit.
%
%  Data for 'Voltage vs Angle' fit:
%      X Input : feedBackVoltage
%      Y Output: inputAngle
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Mar-2015 16:48:27


%% Fit: 'Voltage vs Angle'.
[xData, yData] = prepareCurveData( feedBackVoltage, inputAngle );

% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( ft );
opts.Lower = [-Inf -Inf];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Voltage vs Angle' );
h = plot( fitresult, xData, yData );
legend( h, 'inputAngle vs. feedBackVoltage', 'Voltage vs Angle', 'Location', 'NorthEast' );
% Label axes
xlabel( 'feedBackVoltage' );
ylabel( 'inputAngle' );
grid on


